apiVersion: v1
kind: Service
metadata:
  name: python-metrics-svc
  labels:
    app: python-metrics
spec:
  ports:
  - port: 9105
    targetPort: 8100
  selector:
    app: python-metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-metrics-dep
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: python-metrics
  template:
    metadata:
      labels:
        app: python-metrics
    spec:
      containers:
      - name: python-metrics-pod
        image: xeladock/totalpods:latest
        ports:
        - containerPort: 8100
---
