prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: 'tensor-node'
      static_configs:
        - targets: ['10.42.1.4:9100']
    - job_name: 'python-metrics'
      static_configs:
        - targets: ['10.43.240.142:9105']
